import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Props} from "../interfaces/Props";
import {UserList} from "../components/users/UserList";
import Index from "../components/layout";
import {CgUser, CgUserAdd, CgAddR, CgFileAdd} from 'react-icons/cg';
import {useRouter} from "next/router";
import {InmueblesList} from "../components/inmuebles/InmueblesList";
import {Propiedad_horizonteList} from "../components/propiedades_horizonte/Propiedad_horizonteList";
import {ReglamentoList} from "../components/reglamento/ReglamentoList";
import {MascotasList} from "../components/mascotas/MascotasList";
import {VehiculosList} from "../components/vehiculos/VehiculosList";
import {ParqueaderosList} from "../components/parqueaderos/ParqueaderosList";
import {Areas_comunesList} from "../components/areas_comunes/Areas_comunesList";
import {EventosList} from "../components/eventos/EventosList";
import {Consejos_adminList} from "../components/consejos_admin/Consejos_adminList";


export default function Home({personas, inmuebles, propiedades_horizonte, reglamentos, mascotas, vehiculos, parqueaderos, areas_comunes, eventos, consejos_admin} : Props) {

    const {push} = useRouter();

  return (
    <div>

      <Head>
        <title>Propiedad horizonte App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      <Index>
        <main className={styles.main}>
            <div>
                <div>
                    <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                        <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                            <h1 className="text-xl mb-2"> Lista de usuarios </h1>
                            <p> <CgUser></CgUser> </p>
                            <button
                                className="bg-green-900 px-4 py-2 text-white rounded-lg"
                                onClick={ () => push("/users/new") }
                            >
                                <div className="flex flex-row"><CgUserAdd></CgUserAdd></div>
                            </button>
                        </div>
                    </div>
                    <UserList></UserList>
                </div>

                <div>
                    <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                        <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                            <h1 className="text-xl mb-2"> Lista de Inmuebles </h1>
                            <p>Img inmueble</p>
                            <button
                                className="bg-green-900 px-4 py-2 text-white rounded-lg"
                                onClick={ () => push("/inmuebles/new") }
                            >
                                <div className="flex flex-row"><CgAddR></CgAddR></div>
                            </button>
                        </div>
                    </div>
                    <InmueblesList></InmueblesList>
                </div>

                <div>
                    <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                        <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                            <h1 className="text-xl mb-2"> Lista de Propiedades horizonte </h1>
                            <p>propiedad horizonte</p>
                            <button
                                className="bg-green-900 px-4 py-2 text-white rounded-lg"
                                onClick={ () => push("/propiedades_horizonte/new") }
                            >
                                <div className="flex flex-row"><CgAddR></CgAddR></div>
                            </button>
                        </div>
                    </div>
                    <Propiedad_horizonteList></Propiedad_horizonteList>
                </div>

                <div>
                    <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                        <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                            <h1 className="text-xl mb-2"> Lista de Reglamentos </h1>
                            <p> Img reglamento </p>
                            <button
                                className="bg-green-900 px-4 py-2 text-white rounded-lg"
                                onClick={ () => push("/personas/new") }
                            >
                                <div className="flex flex-row"><CgFileAdd></CgFileAdd></div>
                            </button>
                        </div>

                    </div>
                    <ReglamentoList reglamentos={reglamentos}></ReglamentoList>
                </div>

                <div>
                    <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                        <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                            <h1 className="text-xl mb-2"> Lista de mascotas </h1>
                            <p> Img mascotas </p>
                            <button
                                className="bg-green-900 px-4 py-2 text-white rounded-lg"
                                onClick={ () => push("/personas/new") }
                            >
                                <div className="flex flex-row"><CgFileAdd></CgFileAdd></div>
                            </button>
                        </div>
                    </div>
                    <MascotasList mascotas={mascotas}></MascotasList>
                </div>

                <div>
                    <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                        <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                            <h1 className="text-xl mb-2"> Lista de vehiculos </h1>
                            <p> Img vehiculo </p>
                            <button
                                className="bg-green-900 px-4 py-2 text-white rounded-lg"
                                onClick={ () => push("/personas/new") }
                            >
                                <div className="flex flex-row"><CgFileAdd></CgFileAdd></div>
                            </button>
                        </div>
                    </div>
                    <VehiculosList vehiculos={vehiculos}></VehiculosList>

                </div>

                <div>
                    <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                        <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                            <h1 className="text-xl mb-2"> Lista de parqueaderos </h1>
                            <p> Img parqueadero </p>
                            <button
                                className="bg-green-900 px-4 py-2 text-white rounded-lg"
                                onClick={ () => push("/personas/new") }
                            >
                                <div className="flex flex-row"><CgFileAdd></CgFileAdd></div>
                            </button>
                        </div>
                    </div>
                    <ParqueaderosList parqueaderos={parqueaderos}></ParqueaderosList>
                </div>

                <div>
                    <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                        <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                            <h1 className="text-xl mb-2"> Lista de areas comunes </h1>
                            <p> Img area comun </p>
                            <button
                                className="bg-green-900 px-4 py-2 text-white rounded-lg"
                                onClick={ () => push("/personas/new") }
                            >
                                <div className="flex flex-row"><CgFileAdd></CgFileAdd></div>
                            </button>
                        </div>
                    </div>
                    <Areas_comunesList areas_comunes={areas_comunes}></Areas_comunesList>

                </div>

                <div>
                    <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                        <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                            <h1 className="text-xl mb-2"> Lista de eventos </h1>
                            <p> Img evento </p>
                            <button
                                className="bg-green-900 px-4 py-2 text-white rounded-lg"
                                onClick={ () => push("/personas/new") }
                            >
                                <div className="flex flex-row"><CgFileAdd></CgFileAdd></div>
                            </button>
                        </div>
                    </div>
                    <EventosList eventos={eventos}></EventosList>

                </div>

                <div>
                    <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                        <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                            <h1 className="text-xl mb-2"> Lista de consejos admin </h1>
                            <p> Img consejo admin </p>
                            <button
                                className="bg-green-900 px-4 py-2 text-white rounded-lg"
                                onClick={ () => push("/personas/new") }
                            >
                                <div className="flex flex-row"><CgFileAdd></CgFileAdd></div>
                            </button>
                        </div>
                    </div>
                    <Consejos_adminList consejos_admin={consejos_admin}></Consejos_adminList>
                </div>

            </div>
        </main>
      </Index>

      <footer className={styles.footer}>
        <p> Sebastian Duque {' '} Camilo Sanchez </p>
      </footer>

    </div>
  )
}

export const getServerSideProps = async() => {

  const resPersonas= await fetch('http://localhost:3000/api/personas');
  const personas = await resPersonas.json();

  const resInmuebles = await fetch('http://localhost:3000/api/inmuebles');
  const inmuebles = await resInmuebles.json();

  const resPropiedades_horizonte = await fetch('http://localhost:3000/api/propiedad_horizonte');
  const propiedades_horizonte = await resPropiedades_horizonte.json();

  const resReglamentos = await fetch('http://localhost:3000/api/reglamento');
  const reglamentos = await resReglamentos.json();

  const resMascotas = await fetch('http://localhost:3000/api/mascotas');
  const mascotas = await resMascotas.json();

  const resVehiculos = await fetch('http://localhost:3000/api/vehiculos');
  const vehiculos = await resVehiculos.json();

  const resParqueaderos = await fetch('http://localhost:3000/api/parqueaderos');
  const parqueaderos = await resParqueaderos.json();

  const resAreas_comunes = await fetch('http://localhost:3000/api/areas_comunes');
  const areas_comunes = await resAreas_comunes.json();

  const resEventos = await fetch('http://localhost:3000/api/eventos');
  const eventos = await resEventos.json();

  const resConsejo_admin = await fetch('http://localhost:3000/api/consejos_admin');
  const consejos_admin = await resConsejo_admin.json();


  return {
    props: {
        personas,
        inmuebles,
        propiedades_horizonte,
        reglamentos,
        mascotas,
        vehiculos,
        parqueaderos,
        areas_comunes,
        eventos,
        consejos_admin
    }
  };
};