import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Persona} from "../interfaces/Persona";
import {UserList} from "../components/users/UserList";
import Index from "../components/layout";
import {CgUser, CgUserAdd, CgHome, CgAddR, CgFileAdd} from 'react-icons/cg';
import {useRouter} from "next/router";
import {Inmueble} from "../interfaces/Inmueble";
import {InmueblesList} from "../components/inmuebles/InmueblesList";
import {Propiedad_horizonte} from "../interfaces/propiedad_horizonte";
import {Propiedad_horizonteList} from "../components/propiedades_horizonte/Propiedad_horizonteList";
import {Reglamento} from "../interfaces/Reglamento";
import {ReglamentoList} from "../components/reglamento/ReglamentoList";


interface Props {
  personas : Persona[],
  inmuebles : Inmueble[],
  propiedades_horizonte : Propiedad_horizonte[],
  reglamentos : Reglamento[]
}


export default function Home({personas, inmuebles, propiedades_horizonte, reglamentos} : Props) {

    const {push} = useRouter();

  return (
    <div>

      <Head>
        <title>Propiedad horizonte App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Index>
        <main>
            <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                    <h1 className="text-xl mb-2"> Lista de usuarios </h1>
                    <p> <CgUser></CgUser> </p>
                    <button
                        className="bg-green-900 px-4 py-2 text-white rounded-lg"
                        onClick={ () => push("/personas/new") }
                    >
                        <div className="flex flex-row"><CgUserAdd></CgUserAdd></div>
                    </button>
                </div>
            </div>
            <UserList personas={personas}></UserList>

            <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                    <h1 className="text-xl mb-2"> Lista de Inmuebles </h1>
                    <p>Img inmueble</p>
                    <button
                        className="bg-green-900 px-4 py-2 text-white rounded-lg"
                        onClick={ () => push("/personas/new") }
                    >
                        <div className="flex flex-row"><CgAddR></CgAddR></div>
                    </button>
                </div>
            </div>
            <InmueblesList inmuebles={inmuebles}></InmueblesList>

            <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                    <h1 className="text-xl mb-2"> Lista de Propiedades horizonte </h1>
                    <p>propiedad horizonte</p>
                    <button
                        className="bg-green-900 px-4 py-2 text-white rounded-lg"
                        onClick={ () => push("/personas/new") }
                    >
                        <div className="flex flex-row"><CgAddR></CgAddR></div>
                    </button>
                </div>
            </div>
            <Propiedad_horizonteList propiedades_horizonte={propiedades_horizonte}></Propiedad_horizonteList>

            <div className="relative flex flex-wrap items-center justify-between py-5 bg-gray-200 text-gray-700 shadow-lg">
                <div className="container-fluid w-full flex flex-wrap items-center justify-between px-6">
                    <h1 className="text-xl mb-2"> Lista de Reglamentos </h1>
                    <p> Img reglamento </p>

                    <button
                        className="bg-green-900 px-4 py-2 text-white rounded-lg"
                        onClick={ () => push("/personas/new") }
                    >
                        <div className="flex flex-row"><CgFileAdd></CgFileAdd></div>
                    </button>


                </div>

            </div>
            <ReglamentoList reglamentos={reglamentos}></ReglamentoList>

        </main>
      </Index>

      <footer className={styles.footer}>
        <p> Sebastian Duque {' '} Camilo Sanchez </p>
      </footer>

    </div>
  )
}

export const getServerSideProps = async() => {

  const resPersona= await fetch('http://localhost:3000/api/personas');
  const personas = await resPersona.json();

  const resInmueble = await fetch('http://localhost:3000/api/inmuebles');
  const inmuebles = await resInmueble.json();

  const resPropiedad_horizonte = await fetch('http://localhost:3000/api/propiedad_horizonte');
  const propiedades_horizonte = await resPropiedad_horizonte.json();

  const resReglamento = await fetch('http://localhost:3000/api/reglamento');
  const reglamentos = await resReglamento.json();

  return {
    props: {
      personas : personas,
      inmuebles : inmuebles,
      propiedades_horizonte : propiedades_horizonte,
      reglamentos : reglamentos
    }
  };
};