import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Propiedad horizonte app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}> Bienvenido a propiedad horizonte app </h1>

        <p className={styles.description}> Aqui puede administrar y ver informacion todo acerca de propiedad horizonte para administrar e interactuar como usuario</p>

        <div className={styles.grid}>

          <div className={styles.card}>
            <h2>Lista de propiedad horizonte</h2>
            <p>Las propiedad horizontes que hay</p>
          </div>

          <div className={styles.card}>
            <h2>Lista de reglamentos &rarr;</h2>
            <p>Reglamento a los cuales propiedad horizonte se atiene</p>
          </div>

          <div className={styles.card}>
            <h2>Lista de inmuebles &rarr;</h2>
            <p>Aqui podemos ver informacion de los inmuebles que hay dentro de propiedad horizonte</p>
          </div>

          <div className={styles.card}>
            <h2>Lista de usuario &rarr;</h2>
            <p>Informacion de los usuarios que administran e interactuan con propiedad horizonte tipo propietarios, arrendatarios, residentes y visitantes</p>
          </div>

          <div className={styles.card}>
            <h2>Lista de mascotas &rarr;</h2>
            <p>Mascotas que residen dentro de propiedad horizonte</p>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <div>
          Sebastian Duque Ramirez, Proyecto final bases de datos ,UTP
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </div>
      </footer>

    </div>
  )
}
